### ISSUE TITLE
Combat calculations aren't acknowledging the existence of any skills

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#10]

**Comment by AlmostMatt** [comment]
Added support for basic stat skills in:
https://github.com/ajhyndman/fire-emblem-working-title/commit/7a7a4003e2e6eaf4866fe660c1d687fb995df0dc

**Comment by AlmostMatt** [comment]
For now skills that require hp < 100% can be ignored or that require an ally or that have postcombat effects can be ignored. Some weapons affect specials but specials are not yet implemented.

Remaining skills to be implemented that affect 1v1:
Weapon: Binding Blade, Durandal, Yato, Armads, Naga, Assassin's Bow, Absorb, Pain
A:  Iote's Shield, Svalinn Shield, Fury's Post-combat damage
B: X-Breaker, Poison Strike, Quick Riposte, and Wary Fighter

I've heard that 'guaranteed followup' and 'cannot followup' cancel each other out so that it comes down to speed for whether or not a followup occurs.

**Comment by AlmostMatt** [comment]
The above skills (other than Pain/Fury/PoisonStrike) are implemented now.
I'm not 100% on how wary-fighter and armads/quick-riposte combine.

**Comment by ajhyndman** [comment]
Wow, that was quicker than I imagined!

**Comment by ajhyndman** [comment]
I'm going to call this complete.  We can add more issues for specific omissions or bugs that come up.

**Comment by ajhyndman** [comment]
I did add another issue for special skills.  #32
