### ISSUE TITLE
Any chance on adding Skills and refinements data/image scraping?

### ISSUE THREAD

**Issue by castsaku** [ajhyndman/fire-emblem-working-title#146]
Hey!

I'm using this great tool you made for an university project, but I would love to make it fully functional and as detailed as it can get. I'm loving how useful your work has been, and having the refinements and skills data and assets would be a pretty cool adition, of course following your licensing indications.

Cheers!

**Comment by ajhyndman** [comment]
Refinements would be super valuable, yes.  I think there's an open question for what format would be most useful.  Do you have any thoughts?  It's a bit tricky, because some refinements are shared between weapons, while some are unique.

Skill data should be in there!  And I've got hero avatar icons so far, but no other assets.

I'm happy to help explain the project and help you figure out how to make updates, if you'd like to try contributing.

**Comment by castsaku** [comment]
Is there any more direct way for contacting you, so we can talk? I would like you to know about our project, how your work has been so important for us, and what I've been thinking thinking for improvements. Maybe Discord or Skype? Let me know :).
