### ISSUE TITLE
Improve sorting or filtering of heroes

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#15]

**Comment by AlmostMatt** [comment]
Filters:
Have icon-buttons for either weapon type, move type, or color (or all of the above). At most 1 icon could be selected at a time and clicking on a selected icon would unselect it.
While selected only heroes of that type would be visible.

Sorting:
A drop down (select) field with values:  "Name, Atk, HP, Def, ..."

**Comment by ajhyndman** [comment]
I think there are 12 weapon types and 4 movetypes.  I don't want to make buttons too small, because I want to be able to use this on my phone.  I also think it's preferable if the filtering options are "sticky" like the combat result and the search panel.

That means that the space is at a bit of a premium, so I think 16 options might be too much.  I'm thinking I might just try colors first, and see how that feels?

**Comment by ajhyndman** [comment]
I think #25 is a pretty good start on this.

**Comment by AlmostMatt** [comment]
Yes, 16 is too many. Color filtering is probably the most efficient if you only want one filter type.

**Comment by AlmostMatt** [comment]
Here is a possible mockup
https://www.figma.com/file/WtHjNlexQC4wr1HukfxKCz3l/CombatSim-Filters

Featuring:
tabs for different hero groups (all, hero battle, popular heroes)
color buttons
text based filtering

**Comment by ajhyndman** [comment]
I decided to at least do the minimal change and support searching by other qualities:

87a33474340f4de56432e47c1827ea0370613dfc.

**Comment by AlmostMatt** [comment]
Paraphrasing some comments from the reddit feedback:

- We could group results based on which keyword they matched
- We could group the heroes/results by color
- We could detect mobile vs pc and add additional options on pc
- We could cause exact keywords (like red) to not match substrings
- We could add buttons for each color
- We could add exclusions for certain skill names, so Dragon would never match Dragon's Gaze (Though "Dragon's" would)

And my suggestion:
- We could match prefixes of words instead of substrings (so red would not match sacred). Slightly inconvenient for breaker not matching axebreaker, but would remove some false positives.

**Comment by AlmostMatt** [comment]
I fixed most of the confusing edge cases some time ago by changing it to only match substrings if the query word is not a keyword (so red does not match sacred or armored).

This issue can probably be closed unless you feel strongly about adding other sort orders or buttons.

**Comment by ajhyndman** [comment]
I noticed that.  I feel pretty good about the current usability.  If we decide we want to change something later, we can always open a new issue.
